### ISSUE TITLE
Is there a authority counting fees for every allocation? 

### ISSUE THREAD

**Issue by jongrun** [graphprotocol/contracts#850]
https://github.com/graphprotocol/contracts/blob/5ca9694975463ee13d7321a88db8dbb6c4d951e9/contracts/payments/AllocationExchange.sol#L141-L170
Does it mean that there is a authority ( Gateway? ) who counts fees for every allocation?

**Comment by tmigone** [comment]
Hey @jongrun, sorry for the delayed response here. This one slipped through the cracks. 

There is an authority (the gateway) however it's not "counting" or keeping track of fees as far as I know. The process has two steps:

1) The indexer provides a service (serves queries) and the gateway signs a voucher in exchange. The voicher contains the following information: 
- beneficiary (the indexer serving the queries)
- allocation id (the allocation for which the voucher is for)
- amount (the amount of query fees in GRT that the indexer is owed)

2) The indexer redeems the voucher.


Since the voucher already contains all the information, and it is signed by the gateway, there is no need to keep track of amounts owed per indexer or per allocation.


Hope this is useful information, let me know if I can further assist.
